WIP: [43203] documentation improvements
OS2borgerPC/image pull request #47
Opened 2021-04-28 09:55 UTC by syre

2021-04-28 11:14 UTC, agger-magenta approved these changes
Bortset fra den ene kommentar ser det godt ud! 

Jeg har ikke prøvekørt det dog, så jeg har ikke set renderingen.

2021-04-28 11:14 UTC, agger-magenta commented on docs/source/dev.rst
> +EFI and traditional `isohybrid`-based boot processes, and can be written
Er det ikke dobbelte backticks for at det markeres som kode i RST?

2021-04-28 11:36 UTC, agger-magenta commented on docs/source/dev.rst
> +EFI and traditional `isohybrid`-based boot processes, and can be written
Nej, det ser fint ud - det bliver kursiv, alt er fint, hvis det er det, der er meningen. Jeg havde tænkt, du ville have `code`-formattering.

2021-04-28 11:38 UTC, agger-magenta requested changes

2021-04-28 11:38 UTC, agger-magenta commented on docs/source/dev.rst
> +Create the initial user as Superuser - specify BibOS2 as host name.
Not a new thing, but this should be changed to `os2borgerpc`.

2021-04-28 13:12 UTC, syre commented
Jeg har lavet nogle rettelser, heriblandt den du forespurgte.

Renderingen kan ses her hvis det er: https://os2borgerpc-image.readthedocs.io/en/latest/dev.html

2021-04-28 13:18 UTC, agger-magenta commented on docs/source/dev.rst
> +How-to-build-an-OS2borgerPC-installation-USB-stick-from-an-existing-Clonezilla-image.md
De her henvisninger til filer kan vist slettes eller erstattes af henvisninger til afsnit i stedet.

2021-04-28 13:18 UTC, agger-magenta commented
> Jeg har lavet nogle rettelser, heriblandt den du forespurgte.
> 
> Renderingen kan ses her hvis det er: https://os2borgerpc-image.readthedocs.io/en/latest/dev.html

Ser godt ud, havde lige en enkelt kommentar mere!

2021-04-29 08:07 UTC, syre commented on docs/source/dev.rst
> +How-to-build-an-OS2borgerPC-installation-USB-stick-from-an-existing-Clonezilla-image.md
Yes, det fikser jeg!

2021-04-29 08:23 UTC, syre commented on docs/source/dev.rst
> +How-to-build-an-OS2borgerPC-installation-USB-stick-from-an-existing-Clonezilla-image.md
Den burde der også være rådet bod på nu :+1:

2021-04-29 09:03 UTC, syre commented
Modtaget, den er også fikset nu!

2021-05-04 08:28 UTC, agger-magenta approved these changes

2021-05-05 08:37 UTC, merged