Added script, generalized to be able to enable/disable
OS2borgerPC/image pull request #49
Opened 2021-05-03 12:07 UTC by magenta-mfm

2021-05-03 12:14 UTC, agger-magenta requested changes

2021-05-03 12:14 UTC, agger-magenta commented on admin_scripts/chrome_toggle_start_maximized.sh
> +if [ "$MAXIM_ON_OFF" = 'til' ]; then
jeg foreslår, at vi implementerer denne "Aktivér eller ej"-protokol ligesom i https://os2borgerpc-admin.magenta.dk/site/faxe-kommune/scripts/762/, eftersom det er et pattern, der går igen i _mange_ af vores scripts og det giver mening at homogenisere brugeroplevelsen. På et tidspunkt kunne vi måske lave en slags refactoring, så vi implementerede denne query i en bash-funktion.

2021-05-03 12:59 UTC, magenta-mfm commented on admin_scripts/chrome_toggle_start_maximized.sh
> +if [ "$MAXIM_ON_OFF" = 'til' ]; then
God idé - gjort!

2021-05-05 11:26 UTC, agger-magenta approved these changes
Ser fint ud!

2021-05-05 11:52 UTC, merged