Feature/41327 add shortcut to desktop
OS2borgerPC/image pull request #53
Opened 2021-05-17 12:16 UTC by magenta-mfm

Pt. er aktivering af genveje med i scriptet til at tilføje en genvej.
Jeg tænker på, om det bør hives ud i eget script, hvis der skal laves separate scripts til at oprette nye programmer/genveje selv, som også har brug for at blive aktiveret. Eks. logud-knap.

2021-05-20 11:50 UTC, syre commented on admin_scripts/desktop_launcher_program_shortcut.sh
> +if [ "$PROGRAM" = "tilfoj" ]
Mangler der ikke en "TILFOJ" variabel til "tilfoj" ligesom du har SLET variabel i `desktop_program_shortcut.sh ` scriptet?

2021-05-25 08:41 UTC, syre commented on admin_scripts/desktop_launcher_program_shortcut.sh
> +if [ "$ACTIVATE" != 'false' ] && [ "$ACTIVATE" != 'falsk' ] || \
Burde den sidste "||" ikke også være "&&"?

2021-05-25 08:49 UTC, syre commented on admin_scripts/desktop_program_shortcut.sh
> +if [ "$ACTIVATE" != 'false' ] && [ "$ACTIVATE" != 'falsk' ] || \
og samme her vil jeg mene?

2021-05-25 09:31 UTC, syre commented on admin_scripts/desktop_activate_shortcuts.sh
> +AUTOSTART_DESKTOP_FILE_PATH=/home/$SHADOW/.config/autostart/gio-fix-desktop-file-permissions.desktop
mangler vel `SHADOW=.skjult`?

2021-05-26 07:41 UTC, magenta-mfm commented on admin_scripts/desktop_activate_shortcuts.sh
> +AUTOSTART_DESKTOP_FILE_PATH=/home/$SHADOW/.config/autostart/gio-fix-desktop-file-permissions.desktop
Ja, rettet!

2021-05-26 07:42 UTC, magenta-mfm commented on admin_scripts/desktop_launcher_program_shortcut.sh
> +if [ "$ACTIVATE" != 'false' ] && [ "$ACTIVATE" != 'falsk' ] || \
Jo, det missede jeg af en eller anden grund?! Fikset.

2021-05-26 07:42 UTC, magenta-mfm commented on admin_scripts/desktop_program_shortcut.sh
> +if [ "$ACTIVATE" != 'false' ] && [ "$ACTIVATE" != 'falsk' ] || \
Fikset.

2021-05-26 10:04 UTC, agger-magenta commented on admin_scripts/desktop_activate_shortcuts.sh
> +USER=user
Husk at tilføje den manglende `#!`-linje.

2021-05-26 10:13 UTC, agger-magenta requested changes

2021-05-26 10:13 UTC, agger-magenta commented on admin_scripts/desktop_launcher_program_shortcut.sh
> +  sed -i "s/'\]/', '$PROGRAM'\]/" /etc/dconf/db/os2borgerpc.d/02-launcher-favorites
Her skal man huske `.desktop` i programmets navn, f.eks. `firefox.desktop` ...

2021-05-26 10:13 UTC, agger-magenta commented on admin_scripts/desktop_program_shortcut.sh
> +  cp "/usr/share/applications/$PROGRAM.desktop" /home/$SHADOW/Skrivebord/
Men det skal man ikke her.

Enten eller - nok bedre, man aldrig skal give `.desktop` i parametrene.

2021-05-26 10:16 UTC, agger-magenta commented
Bortset fra de små detaljer virker det hele og kan godkendes og sendes til kunden, så snart det er rettet!

2021-05-26 11:25 UTC, agger-magenta approved these changes

2021-05-26 11:51 UTC, merged